version: 2
jobs:
  deploy_dev:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: npm ci
          command: npm ci && cd functions && npm ci
      - run:
          name: build
          command: npm run generate:prod && cd functions && npm run build
      - run:
          name: deploy to Firebase Hosting
          # devDependenciesに firebase-tools が必須 npm i -D firebase-tools
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project=$FIREBASE_PJ

workflows:
  version: 2
  deploy_dev:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: master
