version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/node:20.19.0

commands:
  install-modules:
    description: 'install node_modules'
    steps:
      - run: npm i

  build-functions:
    description: 'init cloud functions'
    steps:
      - run:
          name: install cloud functions dependencies
          command: cd functions && npm ci
      - run:
          name: build
          command: cd functions && npm run build

jobs:
  deploy_sta:
    executor: default-executor
    steps:
      - checkout
      - install-modules
      - run:
          name: build
          command: APP_ENV=staging npm run generate
      - build-functions
      - run:
          name: deploy to Firebase
          # devDependenciesに firebase-tools が必須 npm i -D firebase-tools
          command: ./node_modules/.bin/firebase deploy -f --token=$STAGING_FIREBASE_TOKEN --project=$STAGING_FIREBASE_PJ

  deploy_sta_hosting:
    executor: default-executor
    steps:
      - checkout
      - install-modules
      - run:
          name: build
          command: APP_ENV=production npm run generate
      - run:
          name: deploy to Firebase Hosting
          # devDependenciesに firebase-tools が必須 npm i -D firebase-tools
          command: ./node_modules/.bin/firebase deploy --only hosting --token=$STAGING_FIREBASE_TOKEN --project=$STAGING_FIREBASE_PJ

  deploy_prod:
    executor: default-executor
    steps:
      - checkout
      - set-env
      - switch-env
      - install-modules
      - run:
          name: build
          command: npm run generate
      - build-functions
      - run:
          name: deploy to Firebase Hosting
          # devDependenciesに firebase-tools が必須 npm i -D firebase-tools
          command: ./node_modules/.bin/firebase deploy -f --token=$FIREBASE_TOKEN --project=$FIREBASE_PJ

  deploy_prod_hosting:
    executor: default-executor
    steps:
      - checkout
      - set-env
      - switch-env
      - install-modules
      - run:
          name: build
          command: npm run generate
      - run:
          name: deploy to Firebase Hosting
          # devDependenciesに firebase-tools が必須 npm i -D firebase-tools
          command: ./node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN --project=$FIREBASE_PJ

workflows:
  version: 2
  deploy_sta:
    jobs:
      - deploy_sta:
          filters:
            branches:
              only: develop

  deploy_prod:
    jobs:
      - deploy_prod:
          filters:
            branches:
              only: master
