version: 2
jobs:
  deploy_dev:
    docker:
      - image: circleci/node:8.16
    steps:
      - checkout
      - run:
          name: npm ci
          command: npm ci
      - run:
          name: build
          command: npm run generate
      - run:
          name: deploy to Firebase Hosting
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_TOKEN --project=$FIREBASE_PJ

workflows:
  version: 2
  deploy_dev:
    jobs:
      - deploy_dev:
          filters:
            branches:
              only: master
