version: 2.1

executors:
  default-executor:
    docker:
      - image: cimg/node:20.19.0

commands:
  install-modules:
    steps:
      - run: npm i

  set-env:
    steps:
      - run:
          name: set env
          command: |
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              echo "Setting staging environment"
              cp -f config/stg.ts config.ts
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              echo "Setting production environment"
              cp -f config/prod.ts config.ts
            fi

  build-functions:
    steps:
      - run:
          name: install cloud functions dependencies
          command: cd functions && npm ci
      - run:
          name: build
          command: cd functions && npm run build

jobs:
  deploy_prod:
    executor: default-executor
    steps:
      - checkout
      - install-modules
      - set-env
      - run:
          name: build
          command: npm run generate
      - build-functions
      - run:
          name: deploy to Firebase Hosting
          # devDependenciesに firebase-tools が必須 npm i -D firebase-tools
          command: ./node_modules/.bin/firebase deploy -f --token=$FIREBASE_TOKEN --project=$FIREBASE_PJ

  deploy_prod_hosting:
    executor: default-executor
    steps:
      - checkout
      - install-modules
      - set-env
      - run:
          name: build
          command: npm run generate
      - run:
          name: deploy to Firebase Hosting
          # devDependenciesに firebase-tools が必須 npm i -D firebase-tools
          command: ./node_modules/.bin/firebase deploy --only hosting --token=$FIREBASE_TOKEN --project=$FIREBASE_PJ

workflows:
  version: 2

  deploy_prod:
    jobs:
      - deploy_prod:
          filters:
            branches:
              only: master
