name: Deploy Hosting to Production

on:
  workflow_dispatch:

jobs:
  deploy-hosting:
    runs-on: ubuntu-latest

    steps:
      - name: Log deployment reason
        run: echo "Deploying to production because - ${{ github.event.inputs.reason || 'Manual trigger' }}"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.19.0
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Set environment
        run: |
          echo "Setting production environment"
          cp -f config/prod.ts config.ts

      - name: Build
        run: npm run generate

      - name: Deploy to Firebase Hosting
        run: npx firebase deploy --only hosting --token=${{ secrets.FIREBASE_TOKEN }} --project=konkarin-photo
